# You can configure the mage bump command to use a local build of porter
# build with mage XBuildAll LocalPorterAgentBuild
# export PORTER_AGENT_REPOSITORY=localhost:5000/porter-agent
# export PORTER_AGENT_VERSION=canary-dev
schemaVersion: 1.0.1
name: dev-build
parameters:
  - name: porterRepository
    source:
      value: "localhost:5000/porter-agent-kubernetes"
  - name: porterVersion
    source:
      value: "canary-dev"
  - name: pullPolicy
    source:
      value: "Always"
